// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGYkgreAe5IuwLOsfzDb6-pCAxoCXGqCo',
    appId: '1:7046262947:web:99538d3e18f8357eec8f16',
    messagingSenderId: '7046262947',
    projectId: 'mrtcompass',
    authDomain: 'mrtcompass.firebaseapp.com',
    storageBucket: 'mrtcompass.firebasestorage.app',
    measurementId: 'G-4P33XRR2P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlgqeRmra82M3nwtuFmBNGzSs1_xHoUbE',
    appId: '1:7046262947:android:37bbc30516d1ac1eec8f16',
    messagingSenderId: '7046262947',
    projectId: 'mrtcompass',
    storageBucket: 'mrtcompass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByi1BpwBq8tcCi2kFWiVtSeAJRjbw293s',
    appId: '1:7046262947:ios:4ad6b7c9268d5f8eec8f16',
    messagingSenderId: '7046262947',
    projectId: 'mrtcompass',
    storageBucket: 'mrtcompass.firebasestorage.app',
    iosBundleId: 'com.example.mrt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByi1BpwBq8tcCi2kFWiVtSeAJRjbw293s',
    appId: '1:7046262947:ios:4ad6b7c9268d5f8eec8f16',
    messagingSenderId: '7046262947',
    projectId: 'mrtcompass',
    storageBucket: 'mrtcompass.firebasestorage.app',
    iosBundleId: 'com.example.mrt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGYkgreAe5IuwLOsfzDb6-pCAxoCXGqCo',
    appId: '1:7046262947:web:59c0afea5d91e4d8ec8f16',
    messagingSenderId: '7046262947',
    projectId: 'mrtcompass',
    authDomain: 'mrtcompass.firebaseapp.com',
    storageBucket: 'mrtcompass.firebasestorage.app',
    measurementId: 'G-Q599LEVRR9',
  );
}
