// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcaE2cb1NZZBF__lsSklOWwbyYnqVo4oo',
    appId: '1:991751588190:web:ca650d684c536d934f67cf',
    messagingSenderId: '991751588190',
    projectId: 'mrt-compass',
    authDomain: 'mrt-compass.firebaseapp.com',
    storageBucket: 'mrt-compass.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJcgyUoubTzn-QShjRl6Y-d-l_Dcszl0',
    appId: '1:991751588190:android:eae772b6c954e68c4f67cf',
    messagingSenderId: '991751588190',
    projectId: 'mrt-compass',
    storageBucket: 'mrt-compass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC91CmBhnrLb2dywF-DTMvXpzeA7iX4gs',
    appId: '1:991751588190:ios:1833a597d53040f04f67cf',
    messagingSenderId: '991751588190',
    projectId: 'mrt-compass',
    storageBucket: 'mrt-compass.firebasestorage.app',
    iosBundleId: 'com.example.mrt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC91CmBhnrLb2dywF-DTMvXpzeA7iX4gs',
    appId: '1:991751588190:ios:1833a597d53040f04f67cf',
    messagingSenderId: '991751588190',
    projectId: 'mrt-compass',
    storageBucket: 'mrt-compass.firebasestorage.app',
    iosBundleId: 'com.example.mrt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcaE2cb1NZZBF__lsSklOWwbyYnqVo4oo',
    appId: '1:991751588190:web:d26b3d94376151014f67cf',
    messagingSenderId: '991751588190',
    projectId: 'mrt-compass',
    authDomain: 'mrt-compass.firebaseapp.com',
    storageBucket: 'mrt-compass.firebasestorage.app',
  );
}
