name: mrt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.0.5
  flutter_screenutil: ^5.0.0+2

flutter_native_splash:
  color: "#ffffff"  # Warna latar belakang splash screen
  image: assets/logo.png  # Ganti dengan path logo Anda
  android: true
  ios: true
  web: false
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pt1.png
    - assets/tr1.png
    - assets/s1.png
