name: mrt
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  cupertino_icons: ^1.0.5
  timeline_tile: ^2.0.0
  intl: ^0.17.0
  geolocator: ^13.0.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2


flutter_native_splash:
  color: "#ffffff" # Warna latar belakang splash screen
  image: assets/logo.png # Ganti dengan path logo Anda
  android: true
  ios: true
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  
dependency_overrides:
  firebase_auth_platform_interface: ^7.4.9


flutter:
  uses-material-design: true
  assets:
    - assets/pt1.png
    - assets/tr1.png
    - assets/longtrain.png
    - assets/profile_image.png
    - assets/icon_direction.png
    - assets/icon_schedule.png
    - assets/icon_guide.png
    - assets/blank-profile.png